version: '3'
services:
  zabbix-proxy-sqlite3:
    image: lgti/zabbix-proxy-sqlite3:ol-5.4.4
    ports:
      - '10051:10051'
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - /home/jenkins/proxy.key:/var/lib/zabbix/enc/proxy.key
    env_file:
     - /home/jenkins/env_proxy
    environment:
     - 'ZBX_SERVER_HOST=127.0.0.1'
     - 'ZBX_SERVER_PORT=10051'
     - 'ZBX_PROXYLOCALBUFFER=24'
     - 'ZBX_PROXYOFFLINEBUFFER=24'
     - 'ZBX_PROXYHEARTBEATFREQUENCY=60'
     - 'ZBX_CONFIGFREQUENCY=600'
     - 'ZBX_ENABLEREMOTECOMMANDS=1'
     - 'ZBX_DATASENDERFREQUENCY=30'
     - 'ZBX_STARTPOLLERS=15'
     - 'ZBX_STARTPOLLERSUNREACHABLE=10'
     - 'ZBX_STARTPREPROCESSORS=10'
     - 'ZBX_STARTHTTPPOLLERS=15'
     - 'ZBX_STARTTRAPPERS=20'
     - 'ZBX_STARTPINGERS=15'
     - 'ZBX_STARTDISCOVERERS=5'
     - 'ZBX_STARTVMWARECOLLECTORS=15'
     - 'ZBX_VMWAREFREQUENCY=60'
     - 'ZBX_VMWAREPERFFREQUENCY=60'
     - 'ZBX_VMWARECACHESIZE=256M'
     - 'ZBX_VMWARETIMEOUT=300'
     - 'ZBX_CACHESIZE=512M'
     - 'ZBX_STARTDBSYNCERS=8'
     - 'ZBX_HISTORYCACHESIZE=32M'
     - 'ZBX_HISTORYINDEXCACHESIZE=32M'
     - 'ZBX_TIMEOUT=30'
     - 'ZBX_TLSPSKFILE=proxy.key'
     - 'ZBX_TLSPSKIDENTITY=proxy_psk'
     - 'ZBX_TLSCONNECT=psk'
     - 'ZBX_TLSACCEPT=psk'
